### ISSUE TITLE
Issue with the prompt - scale score and sentli

### ISSUE THREAD

**Issue by jeevananandanne** [asappresearch/scale-score#2]
@blattimer-asapp  @fvivas-asapp 

Below is the  prompt used in the code:

'{{premise}} Question: Does this imply that "{{hypothesis}}"? Yes or no?' 

Is it expected to be "no" or it should be "No". I see you are considering "Yes" & "No" tokens.

**Comment by blattimer-asapp** [comment]
Thanks for the note! I updated the prompt to '{{premise}} Question: Does this imply that "{{hypothesis}}"? Yes or No?' and reran the tests, there was no difference for all the results :)
